### ISSUE TITLE
Cannot define custom string in the custom pipeline mapping

### ISSUE THREAD

**Issue by ndex11** [SigmaHQ/sigma-cli#18]
Command:
sigma convert -t qradar -p qradar_pipeline.yaml rules\windows\dns_query\dns_query_win_anonymfiles_com.yml

Error: 
**Error while conversion: The QRadar savedsearches Sigma backend supports only the following fields for process_creation log source**

I think there should be something after "log source" in the error message but there is not.

**Not working:**
name: Qradar Pipeline
priority: 100
transformations:
  - id: field_mapping
    type: field_name_mapping
    mapping:
      QueryName: "Domain Name"

**Not working:**
name: Qradar Pipeline
priority: 100
transformations:
  - id: field_mapping
    type: field_name_mapping
    mapping:
      QueryName: test

**Working:**
name: Qradar Pipeline
priority: 100
transformations:
  - id: field_mapping
    type: field_name_mapping
    mapping:
      QueryName: Image

**Working:**
name: Qradar Pipeline
priority: 100
transformations:
  - id: field_mapping
    type: field_name_mapping
    mapping:
      QueryName: "Image"

**Comment by thomaspatzke** [comment]
It's a QRadar backend issue, moving it to the project.

**Comment by thomaspatzke** [comment]
Can't move across orgs, please reopen in [this repository](https://github.com/nNipsx-Sec/pySigma-backend-qradar).
