### ISSUE TITLE
sigma plugin install error

### ISSUE THREAD

**Issue by noaakl** [SigmaHQ/sigma-cli#25]
Hello,
I tried to use `sigma plugin install <backend>` as described in the README (for several different backends), but I got `Error: No such command 'plugin'.`

**Comment by Neo23x0** [comment]
You're probably using an outdated version. 

Could you run a 
```
pip list | grep sigma
```

**Comment by noaakl** [comment]
pysigma                              0.9.10
sigma                                0.0.1
sigma-cli                            0.7.5

**Comment by thomaspatzke** [comment]
The `sigma` package doesn't belongs to it, possibly you don't execute sigma CLI but something different. Please try again from a clean Python environment or use pipx, which is the preferred way to manage your sigma CLI installation.

**Comment by noaakl** [comment]
Thank you, it is all working now. I will appreciate it if you can take a look at the pull request on the `pySigma-plugin-directory` so I will be able to use the `ibm-qradar-aql` plugin. Thanks a lot

**Comment by thomaspatzke** [comment]
Sure! Just done it!
