### ISSUE TITLE
Error while conversion: field 'Description' is not supported

### ISSUE THREAD

**Issue by syedaqeel** [SigmaHQ/sigma-cli#26]
We have tried both plugin qradar & ibm-qradar-aql and the available pipelines but there is an error like the one in title. Here is the command 

cmd>sigma convert -t ibm-qradar-aql -p qradar-aql-fields D:\user\sigma-master\rules\windows\process_creation

Parsing Sigma rules  [####################################]  100%
Error while conversion: field 'Description' is not supported

Any workaround for this

**Comment by thomaspatzke** [comment]
This is a QRadar backend issue and not an issue of Sigma CLI. Please reopen in the appropriate repository.
