### ISSUE TITLE
 Why doesn't the Sigma CLI support converting Sigma rules into SQL or grep statements?

### ISSUE THREAD

**Issue by sniperking1234** [SigmaHQ/sigma-cli#28]
I've seen in the documentation that it's supported, but when I use it, I can't find the corresponding backend.
![image](https://github.com/SigmaHQ/sigma-cli/assets/7834655/b6b8d8ec-46a4-4d58-b765-6b03e6b455bb)

**Comment by thomaspatzke** [comment]
The formats are supported of legacy sigmac. To my knowledge SQL is in development by someone, grep will follow at some time.

**Comment by Neo23x0** [comment]
> To my knowledge SQL is in development by someone, grep will follow at some time.

**Comment by sniperking1234** [comment]
@Neo23x0 thanks

**Comment by thomaspatzke** [comment]
Here's a new backend for SQLite: https://github.com/wagga40/pySigma-backend-sqlite I think integration into CLI will follow soon.
