### ISSUE TITLE
Allow sigma check to disable some validators

### ISSUE THREAD

**Issue by Res260** [SigmaHQ/sigma-cli#34]
`sigma check` should have an argument like `--exclude` that ignores a given list of validators. It would be used like this:

`sigma check ./rules --exclude InvalidRelatedIdValidator InvalidRelatedSubfieldValidator InvalidRelatedTypeValidator`

It would allow backend devs and detection-as-code pipelines to disable default validators that we do not want to include in validations.

Thoughts?

**Comment by thomaspatzke** [comment]
It's already possible by the Sigma validation config as described here: https://sigmahq-pysigma.readthedocs.io/en/latest/Rule_Validation.html#validator-checks

**Comment by thomaspatzke** [comment]
Generally an additional parameter would also be fine as lightweight config possibility. But the config offers much more possibilities like exclusion of validators for specific rules.

**Comment by Res260** [comment]
Lol i implemented it kinda quickly, does it fit the project? I won't be mad if you prefer to keep only one option, i personally prefer the CLI argument for simple use cases

**Comment by thomaspatzke** [comment]
Totally fine with it 🙂 can you just said a test for the new parameter?
